# Generated by Django 5.1.1 on 2026-03-05 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 5, 8, 42, 37, 671083, tzinfo=datetime.timezone.utc)),
        ),
    ]
