# Generated by Django 5.1.1 on 2026-03-05 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 5, 8, 56, 48, 233479, tzinfo=datetime.timezone.utc)),
        ),
    ]
